//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Resx.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi budget.
        /// </summary>
        internal static string AddBudget {
            get {
                return ResourceManager.GetString("AddBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi.
        /// </summary>
        internal static string AddMovement {
            get {
                return ResourceManager.GetString("AddMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apr.
        /// </summary>
        internal static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ago.
        /// </summary>
        internal static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scommesse.
        /// </summary>
        internal static string Bets {
            get {
                return ResourceManager.GetString("Bets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bimestrale.
        /// </summary>
        internal static string Bimonthly {
            get {
                return ResourceManager.GetString("Bimonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        internal static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hai sforato il budget {0}!.
        /// </summary>
        internal static string BudgetEnded {
            get {
                return ResourceManager.GetString("BudgetEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il budget selezionato è finito.
        /// </summary>
        internal static string BudgetEndedAlert {
            get {
                return ResourceManager.GetString("BudgetEndedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il budget {0} è scaduto ed è stato eliminato.
        /// </summary>
        internal static string BudgetExpired {
            get {
                return ResourceManager.GetString("BudgetExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avviso.
        /// </summary>
        internal static string BudgetExpiredTitle {
            get {
                return ResourceManager.GetString("BudgetExpiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vestiti.
        /// </summary>
        internal static string Clothes {
            get {
                return ResourceManager.GetString("Clothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crediti.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuta.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le valute vengono aggiornate una volta al giorno.
        /// </summary>
        internal static string CurrencyConversionWarning {
            get {
                return ResourceManager.GetString("CurrencyConversionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiornamento dei dati finito.
        /// </summary>
        internal static string DatabaseCurrencyUpdateEnded {
            get {
                return ResourceManager.GetString("DatabaseCurrencyUpdateEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ora puoi chiudere l&apos;app in modo sicuro.
        /// </summary>
        internal static string DatabseCurrencyUpdateEndedMessage {
            get {
                return ResourceManager.GetString("DatabseCurrencyUpdateEndedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La data selezionata non è valida per il budget.
        /// </summary>
        internal static string DateOutOfBudget {
            get {
                return ResourceManager.GetString("DateOutOfBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dic.
        /// </summary>
        internal static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuta base.
        /// </summary>
        internal static string DefaultCurrency {
            get {
                return ResourceManager.GetString("DefaultCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuoi davvero eliminare il movimento?.
        /// </summary>
        internal static string DeleteItemMessage {
            get {
                return ResourceManager.GetString("DeleteItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devi inserire una Descrizione.
        /// </summary>
        internal static string DescriptionEnteredNotValid {
            get {
                return ResourceManager.GetString("DescriptionEnteredNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarica dati.
        /// </summary>
        internal static string DownloadData {
            get {
                return ResourceManager.GetString("DownloadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non hai ancora registrato nessun dato.
        /// </summary>
        internal static string EmptyLabel {
            get {
                return ResourceManager.GetString("EmptyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intrattenimento.
        /// </summary>
        internal static string Entertainment {
            get {
                return ResourceManager.GetString("Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uscite: .
        /// </summary>
        internal static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string ExpenseType {
            get {
                return ResourceManager.GetString("ExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        internal static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File scaricati.
        /// </summary>
        internal static string FileDownloadedNotificationTItle {
            get {
                return ResourceManager.GetString("FileDownloadedNotificationTItle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I movimenti e gli abbonamenti sono stati scaricati nella cartella download.
        /// </summary>
        internal static string FileDownloadNotificationDescription {
            get {
                return ResourceManager.GetString("FileDownloadNotificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fine.
        /// </summary>
        internal static string FinalDate {
            get {
                return ResourceManager.GetString("FinalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cibo.
        /// </summary>
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regali.
        /// </summary>
        internal static string Gifts {
            get {
                return ResourceManager.GetString("Gifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storico.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacanze.
        /// </summary>
        internal static string Holydays {
            get {
                return ResourceManager.GetString("Holydays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghiaccio.
        /// </summary>
        internal static string Ice {
            get {
                return ResourceManager.GetString("Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrate: .
        /// </summary>
        internal static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inizio.
        /// </summary>
        internal static string InitialDate {
            get {
                return ResourceManager.GetString("InitialDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È una spesa?.
        /// </summary>
        internal static string IsExpense {
            get {
                return ResourceManager.GetString("IsExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È ricorrente?.
        /// </summary>
        internal static string IsSubscription {
            get {
                return ResourceManager.GetString("IsSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiano.
        /// </summary>
        internal static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gen.
        /// </summary>
        internal static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lug.
        /// </summary>
        internal static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giu.
        /// </summary>
        internal static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingua.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimo rinnovo.
        /// </summary>
        internal static string LastRenewal {
            get {
                return ResourceManager.GetString("LastRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiaro.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbonamenti.
        /// </summary>
        internal static string ManageSubs {
            get {
                return ResourceManager.GetString("ManageSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        internal static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag.
        /// </summary>
        internal static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mese.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensile.
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensile.
        /// </summary>
        internal static string MonthlyExpense {
            get {
                return ResourceManager.GetString("MonthlyExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimento.
        /// </summary>
        internal static string Movement {
            get {
                return ResourceManager.GetString("Movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimenti.
        /// </summary>
        internal static string Movements {
            get {
                return ResourceManager.GetString("Movements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totale.
        /// </summary>
        internal static string NetWorth {
            get {
                return ResourceManager.GetString("NetWorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prossimo rinnovo.
        /// </summary>
        internal static string NextRenewal {
            get {
                return ResourceManager.GetString("NextRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuno.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nord.
        /// </summary>
        internal static string Nord {
            get {
                return ResourceManager.GetString("Nord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        internal static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ott.
        /// </summary>
        internal static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altro.
        /// </summary>
        internal static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagati.
        /// </summary>
        internal static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamento di: {0}.
        /// </summary>
        internal static string PaymentOf {
            get {
                return ResourceManager.GetString("PaymentOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cura personale.
        /// </summary>
        internal static string PersonalCare {
            get {
                return ResourceManager.GetString("PersonalCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimestrale.
        /// </summary>
        internal static string Quarterly {
            get {
                return ResourceManager.GetString("Quarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rimanenti.
        /// </summary>
        internal static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non hai selezionato un Rinnovo.
        /// </summary>
        internal static string RenewalSelectedNotValid {
            get {
                return ResourceManager.GetString("RenewalSelectedNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rinnovo.
        /// </summary>
        internal static string RenewalType {
            get {
                return ResourceManager.GetString("RenewalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segnala un Bug.
        /// </summary>
        internal static string ReportBug {
            get {
                return ResourceManager.GetString("ReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stato possibile salvare i dati.
        /// </summary>
        internal static string SavingFailed {
            get {
                return ResourceManager.GetString("SavingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestrale.
        /// </summary>
        internal static string Semiannual {
            get {
                return ResourceManager.GetString("Semiannual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostazioni.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        internal static string Sport {
            get {
                return ResourceManager.GetString("Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistiche.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbonamenti.
        /// </summary>
        internal static string Subscriptions {
            get {
                return ResourceManager.GetString("Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acqua.
        /// </summary>
        internal static string Teal {
            get {
                return ResourceManager.GetString("Teal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech.
        /// </summary>
        internal static string Tech {
            get {
                return ResourceManager.GetString("Tech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totale.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimo anno.
        /// </summary>
        internal static string TotalYTD {
            get {
                return ResourceManager.GetString("TotalYTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trasporti.
        /// </summary>
        internal static string Transports {
            get {
                return ResourceManager.GetString("Transports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non hai selezionato un Tipo.
        /// </summary>
        internal static string TypeSelectedNotValid {
            get {
                return ResourceManager.GetString("TypeSelectedNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I tuoi dati stanno venendo aggiornati. Essendo un&apos;operazione delicata, ti preghiamo non chiudere l&apos;applicazione fino a quando non riceverai la notifica di fine dell&apos;aggiornamento.
        /// </summary>
        internal static string UpdatingCurrencyMessage {
            get {
                return ResourceManager.GetString("UpdatingCurrencyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usati.
        /// </summary>
        internal static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importo.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;importo inserito non è valido.
        /// </summary>
        internal static string ValueEnteredNotValid {
            get {
                return ResourceManager.GetString("ValueEnteredNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione!.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settimanale.
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anno.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuale.
        /// </summary>
        internal static string Yearly {
            get {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuale.
        /// </summary>
        internal static string YearlyExpense {
            get {
                return ResourceManager.GetString("YearlyExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrate annuali.
        /// </summary>
        internal static string YearlyIncome {
            get {
                return ResourceManager.GetString("YearlyIncome", resourceCulture);
            }
        }
    }
}
